name = "caipiao-app"
type = "webpack"
account_id = "5a66f1472706ab4252f1b2082df3cb56"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-01-01"

[site]
bucket = "./"
entry-point = "worker.js"
