name = "caipiao-app"
type = "webpack"
account_id = "263909a5-2a5e-4b1a-95fa-a3bd9aec8535"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-01-01"

[site]
bucket = "./"
entry-point = "worker.js"